version: "3.3"
services:
  mariadb:
    image: mariadb:latest
    restart: always
    container_name: mariadb1
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - mariadb_volume:/var/lib/mysql
      - ./imse_create.sql:/docker-entrypoint-initdb.d/imse_create.sql

# Names our volume
volumes:
  mariadb_volume:
